import { expect, test } from "@playwright/test";
const S = "tests/e2e/screenshots";
test("design review shots", async ({ page, browser }) => {
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Sign in" })).toBeVisible();
  await page.waitForTimeout(800);
  await page.screenshot({ path: `${S}/40-login.png` });
  await page.getByLabel("Email").fill("owner@test.local");
  await page.getByLabel("Password").fill("test1234");
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page.getByRole("heading", { name: "Dashboard" })).toBeVisible();
  await page.waitForTimeout(1500);
  await page.screenshot({ path: `${S}/41-dashboard-fold.png` });
  await page.goto("/clients/");
  await page.waitForTimeout(1200);
  await page.screenshot({ path: `${S}/42-clients-list.png` });
  await page.goto("/sales-orders/");
  await page.locator("main tbody tr").first().click();
  await page.waitForTimeout(900);
  await page.screenshot({ path: `${S}/43-so-drawer.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(700);
  await page.screenshot({ path: `${S}/44-phone-drawer.png` });
  await page.goto("/");
  await page.waitForTimeout(1500);
  await page.screenshot({ path: `${S}/45-phone-dashboard.png`, fullPage: true });
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const p2 = await ctx.newPage();
  await p2.goto("http://localhost:3000/");
  await p2.waitForTimeout(1500);
  await p2.screenshot({ path: `${S}/46-phone-login.png` });
});
